In [2]:
# Se importa los paquetes necesarios
import pandas as pd
import requests
import zipfile, os, sys

In [3]:
# Enlace del archivo
url = "https://databank.worldbank.org/data/download/ESG_CSV.zip"

# Descargar el archivo
response = requests.get(url)
with open('ESG_Dataset.zip', 'wb') as f:
    f.write(response.content)

In [4]:
# Unzip the dataset
with zipfile.ZipFile('ESG_Dataset.zip', 'r') as zip_ref:
    zip_ref.extractall('ESG_Dataset')

# Delete the archive
os.remove('ESG_Dataset.zip')

In [5]:
# Se carga el dataset en un DataFrame pandas

ESG_df = pd.read_csv("/content/ESG_Dataset/ESGCSV.csv")
# Supprimer colonnes inutiles
ESG_df.drop(columns=['Country Code', "Indicator Code"], inplace=True)
ESG_df

,Country Name,Indicator Name,1960,1961,1962,1963,1964,1965,1966,1967,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Arab World,Access to clean fuels and technologies for coo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,86.705717,86.942778,87.228705,87.390856,87.617862,87.798740,87.948264,88.092536,NaN,NaN
1,Arab World,Access to electricity (% of population),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,88.832276,89.053852,89.539016,90.662754,89.176939,90.352802,90.635050,90.845661,NaN,NaN
2,Arab World,Adjusted savings: natural resources depletion ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.050554,6.130655,5.265859,6.245422,8.187714,7.234436,4.598506,NaN,NaN,NaN
3,Arab World,Adjusted savings: net forest depletion (% of GNI),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.084361,0.096672,0.092911,0.102684,0.057123,0.064516,0.075686,NaN,NaN,NaN
4,Arab World,Agricultural land (% of land area),NaN,30.981414,30.982663,31.007054,31.018001,31.042466,31.0504,31.103223,...,39.834421,39.872575,39.937814,39.984452,39.969738,39.907031,39.973290,39.970742,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16964,Zimbabwe,Terrestrial and marine protected areas (% of t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,27.214542,27.214585,27.214585,27.214747,27.214747,27.214747,27.214747,NaN
16965,Zimbabwe,Tree Cover Loss (hectares),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16966,Zimbabwe,"Unemployment, total (% of total labor force) (...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.770000,5.412000,5.918000,6.349000,6.767000,7.370000,8.651000,9.540000,9.256000,9.116
16967,Zimbabwe,Unmet need for contraception (% of married wom...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.382129,10.400000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16968,Zimbabwe,Voice and Accountability: Estimate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-1.256889,-1.166087,-1.178460,-1.195905,-1.136798,-1.163669,-1.113408,-1.135830,-1.102206,NaN

In [6]:
# Cambiamos el DataFrame para poner los indicatores en columnas

# Formato longo
df_long = ESG_df.melt(
    id_vars=["Country Name", "Indicator Name"],
    var_name="Year",
    value_name="Value"
)
# Indicadores en columnas
ESG_ByInd_df = df_long.pivot_table(
    index=["Country Name", "Year"],
    columns="Indicator Name",
    values="Value"
).reset_index()

# Evitar multi-index
ESG_ByInd_df.columns.name = None
ESG_ByInd_df

,Country Name,Year,Access to clean fuels and technologies for cooking (% of population),Access to electricity (% of population),Adjusted savings: natural resources depletion (% of GNI),Adjusted savings: net forest depletion (% of GNI),Agricultural land (% of land area),"Agriculture, forestry, and fishing, value added (% of GDP)","Annual freshwater withdrawals, total (% of internal resources)","Annualized average growth rate in per capita real survey mean consumption or income, total population (%)",...,"School enrollment, primary (% gross)","School enrollment, primary and secondary (gross), gender parity index (GPI)",Scientific and technical journal articles,Standardised Precipitation-Evapotranspiration Index,Strength of legal rights index (0=weak to 12=strong),Terrestrial and marine protected areas (% of total territorial area),Tree Cover Loss (hectares),"Unemployment, total (% of total labor force) (modeled ILO estimate)",Unmet need for contraception (% of married women ages 15-49),Voice and Accountability: Estimate
0,Afghanistan,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.761520,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1961,NaN,NaN,NaN,NaN,57.878356,NaN,NaN,NaN,...,NaN,NaN,NaN,-0.076736,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1962,NaN,NaN,NaN,NaN,57.955016,NaN,NaN,NaN,...,NaN,NaN,NaN,-0.665528,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1963,NaN,NaN,NaN,NaN,58.031676,NaN,NaN,NaN,...,NaN,NaN,NaN,0.216942,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1964,NaN,NaN,NaN,NaN,58.116002,NaN,NaN,NaN,...,NaN,NaN,NaN,0.488956,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15275,Zimbabwe,2019,30.2,46.682095,4.088445,2.028044,41.876696,9.819262,30.761677,1.03,...,97.476608,NaN,431.62,-0.301619,6.0,27.214747,NaN,7.370,NaN,-1.163669
15276,Zimbabwe,2020,30.3,52.747667,4.108902,2.315889,41.876696,8.772859,30.761677,NaN,...,97.384163,NaN,480.16,-0.204054,NaN,27.214747,NaN,8.651,NaN,-1.113408
15277,Zimbabwe,2021,30.3,48.979927,5.053145,1.865862,41.876696,8.849899,NaN,NaN,...,96.015144,NaN,NaN,-0.549090,NaN,27.214747,NaN,9.540,NaN,-1.135830
15278,Zimbabwe,2022,NaN,NaN,NaN,NaN,NaN,7.191922,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,27.214747,NaN,9.256,NaN,-1.102206
15279,Zimbabwe,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.116,NaN,NaN